version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 10
    reviewers:
      - "baileydunning"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "npm"
    directory: "/packages/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/server"
    schedule:
      interval: "weekly"