dry-run: null
hookfiles: []
language: nodejs
server: ''
server-wait: 3
init: false
custom: []
only: []
skip: []
reporter: []
require: []
details: false
inline-errors: false
sorted: false
names: false
color: true
loglevel: warning
path: []
blueprint: packages/server/openapi.yaml
endpoint: http://localhost:3000/api/v1
expectedContentTypes:
  application/json:
  - application/json
  - application/json; charset=utf-8
