language: nodejs
server: 'node packages/server/src/index.ts'
init: false
details: false
inline-errors: false
sorted: false
names: false
color: true
loglevel: warning
blueprint: packages/server/openapi.yaml
endpoint: http://localhost:3000/api/v1
