version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: campsights-app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
    volumes:
      - ./packages:/app/packages:ro 
    restart: unless-stopped