openapi: 3.0.3
info:
  title: Campsights API
  version: 2.0.0
  description: |
    API for Campsights app - provides campsite data from the Bureau of Land Management (BLM) Spider API with enhanced elevation and weather information.

    ## Data Sources
    - **Campsites**: Bureau of Land Management Spider API (https://blm-spider.onrender.com/api/v1/campsites)
    - **Elevation**: Open Elevation API (https://api.open-elevation.com)
    - **Weather**: National Weather Service API

    ## API Behavior
    - GET /campsites: Returns raw BLM campsite data
    - GET /campsites/{id}: Returns enhanced data with elevation and weather

servers:
- url: https://campsights.onrender.com/api/v1
  description: Production server (Render) - Proxies BLM Spider API with elevation/weather enhancements
- url: http://localhost:3000/api/v1
  description: Development server (Local) - Proxies BLM Spider API with elevation/weather enhancements
tags:
- name: Campsites
  description: Operations related to campsite resources
- name: Health
  description: Health check endpoint

paths:
  /campsites:
    get:
      tags:
      - Campsites
      operationId: listCampsites
      summary: Get all campsites from BLM Spider API
      description: Retrieves campsite data from the Bureau of Land Management Spider API. Elevation and weather data are not included in the list view for performance reasons.
      responses:
        '200':
          description: List of campsites (without elevation/weather data)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campsite'
              example:
              - id: "28430a4f-ce40-478d-a7b1-0c23d9c49dbb"
                name: "Middle Fork of the Powder River Campground"
                url: "https://www.blm.gov/visit/middle-fork-powder-river-campground-0"
                description: "Astride a blue-ribbon trout stream, this remote and picturesque campground features five camping sites with fire rings, restroom and drinking water."
                lat: 43.579304
                lng: -107.140476
                state: "Wyoming"
                mapLink: "https://www.openstreetmap.org/export/embed.html?bbox=-107.150476,43.569304,-107.130476,43.589304&layer=mapnik&marker=43.579304,-107.140476"
                directions: "From Ten Sleep, the area is reached by driving 20 miles south on State Highway 434 to Big Trails."
                activities: [ "CAMPING" ]
                source: "BLM"
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'

  /campsites/{id}:
    get:
      tags:
      - Campsites
      operationId: getCampsiteById
      summary: Get a campsite by ID (with elevation and weather)
      description: Retrieves detailed campsite information including elevation and weather data. This endpoint fetches additional data not included in the list view.
      parameters:
      - $ref: '#/components/parameters/campsiteId'
      responses:
        '200':
          description: Campsite with elevation and weather
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampsiteWithWeather'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'

  /health:
    get:
      tags:
      - Health
      operationId: healthCheck
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

components:
  parameters:
    campsiteId:
      name: id
      in: path
      description: Unique identifier for a campsite from BLM Spider API
      required: true
      schema:
        type: string
      example: "28430a4f-ce40-478d-a7b1-0c23d9c49dbb"

  schemas:
    Error:
      type: object
      required:
      - error
      properties:
        error:
          type: string

    CampsiteImage:
      type: object
      properties:
        src:
          type: string
          format: uri
          example: "https://cdn.recreation.gov/public/2023/06/20/22/39/ed4c589b-d3e4-49fb-a0fd-f8bb7a0c4e3d.jpeg"
        alt:
          type: string
          example: "John Day River from Muleshoe Campground"
        credit:
          type: string
          example: "Bureau of Land Management"

    Campsite:
      type: object
      required:
      - id
      - name
      - url
      - lat
      - lng
      - state
      - mapLink
      - source
      properties:
        id:
          type: string
          example: "28430a4f-ce40-478d-a7b1-0c23d9c49dbb"
        name:
          type: string
          example: "Middle Fork of the Powder River Campground"
        url:
          type: string
          format: uri
          example: "https://www.blm.gov/visit/middle-fork-powder-river-campground-0"
        description:
          type: string
          example: "Astride a blue-ribbon trout stream, this remote and picturesque campground features five camping sites with fire rings, restroom and drinking water."
        lat:
          type: number
          format: float
          example: 43.579304
        lng:
          type: number
          format: float
          example: -107.140476
        state:
          type: string
          example: "Wyoming"
        mapLink:
          type: string
          format: uri
          example: "https://www.openstreetmap.org/export/embed.html?bbox=-107.150476,43.569304,-107.130476,43.589304&layer=mapnik&marker=43.579304,-107.140476"
        directions:
          type: string
          example: "From Ten Sleep, the area is reached by driving 20 miles south on State Highway 434 to Big Trails."
        activities:
          type: array
          items:
            type: string
          example: [ "CAMPING", "FISHING", "HIKING" ]
        campgrounds:
          type: array
          items:
            type: string
          example: [ "RV", "TENT" ]
        wildlife:
          type: array
          items:
            type: string
          example: [ "Deer", "Eagles" ]
        fees:
          type: string
          example: "$5 per night per campsite"
        stayLimit:
          type: string
          example: "14 days"
        images:
          type: array
          items:
            $ref: '#/components/schemas/CampsiteImage'
        source:
          type: string
          enum: [ "BLM" ]
          example: "BLM"

    WeatherPeriod:
      type: object
      required:
      - name
      - startTime
      - endTime
      - temperature
      - temperatureUnit
      - windSpeed
      - windDirection
      - shortForecast
      - detailedForecast
      properties:
        name:
          type: string
          example: "Tonight"
        startTime:
          type: string
          format: date-time
          example: "2025-07-03T18:00:00-06:00"
        endTime:
          type: string
          format: date-time
          example: "2025-07-04T06:00:00-06:00"
        temperature:
          type: number
          example: 60
        temperatureUnit:
          type: string
          example: "F"
        windSpeed:
          type: string
          example: "5 mph"
        windDirection:
          type: string
          example: "NW"
        shortForecast:
          type: string
          example: "Clear"
        detailedForecast:
          type: string
          example: "Clear skies tonight with a light breeze."

    CampsiteWithWeather:
      allOf:
      - $ref: '#/components/schemas/Campsite'
      - type: object
        properties:
          elevation:
            type: number
            nullable: true
            description: "Elevation in meters above sea level (fetched from Open Elevation API)"
            example: 2650
          weather:
            type: array
            items:
              $ref: '#/components/schemas/WeatherPeriod'
            description: "Weather forecast data from National Weather Service"

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TooManyRequests:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
