name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies and build
        run: |
          npm install --prefix server
          npm run build --prefix server
          npm install --prefix client
          npm run build --prefix client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start app using docker-compose
        run: docker-compose up --build -d --remove-orphans

      - name: Wait for server and test API
        run: |
          sleep 10
          curl -f http://localhost:3000/api/v1/campsites

      - name: Test frontend is being served
        run: |
          curl -f http://localhost:3000

      - name: Tear down containers
        run: docker-compose down