name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Build server (TypeScript)
        run: npm run build
        working-directory: server

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Build client (Vite)
        run: npm run build
        working-directory: client

      - name: Build server Docker image
        run: docker build -t campsights-server ./server

      - name: Build client Docker image
        run: docker build -t campsights-client ./client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and start all services with Docker Compose
        run: docker-compose up --build -d

      - name: Wait for server and test API
        run: |
          sleep 10
          curl -f http://localhost:3000/api/v1/campsites

      - name: Test client is running
        run: |
          curl -f http://localhost:5173

      - name: Stop containers
        run: docker-compose down