name: Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build all packages
        run: npx lerna run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start app using docker-compose
        run: docker-compose up --build -d --remove-orphans

      - name: Wait for server and test API
        run: |
          sleep 10
          curl -f http://localhost:4000/api/v1/campsites

      - name: Test frontend is being served
        run: |
          curl -f http://localhost:4000

      - name: Tear down containers
        run: docker-compose down