name: Validate OpenAPI Spec

on:
  push:
    paths:
    - 'packages/server/openapi.yaml'
    - '.github/workflows/openapi.yml'
  pull_request:
    paths:
    - 'packages/server/openapi.yaml'

jobs:
  validate-openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Swagger CLI
      run: npm install -g @apidevtools/swagger-cli

    - name: Validate OpenAPI spec
      working-directory: packages/server
      run: swagger-cli validate openapi.yaml

    - name: Validate endpoints
      working-directory: packages/server
      run: npx ts-node src/utils/validateEndpoints.ts
