name: Validate Manifest

on:
  push:
    paths:
      - 'packages/client/public/manifest.webmanifest'
      - 'packages/client/**'
      - '.github/workflows/validate-manifest.yml'
  pull_request:
    paths:
      - 'packages/client/public/manifest.webmanifest'
      - 'packages/client/**'
      - '.github/workflows/validate-manifest.yml'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd packages/client
          npm ci
      - name: Build client
        run: |
          cd packages/client
          npm run build
      - name: Install server dependencies
        run: |
          cd packages/server
          npm ci
      - name: Copy client build to server
        run: |
          rm -rf packages/server/public/*
          cp -r packages/client/dist/* packages/server/public/
      - name: Start backend server
        run: |
          cd packages/server
          npm run build || true
          npm start &
          sleep 5
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: Run Lighthouse CI against backend server
        run: lhci autorun --collect.url=http://localhost:3000
